{% set name = "mkdocs-video" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-video-{{ version }}.tar.gz
  sha256: 0defc018f4b7927f8afffc4d8e039c84dfba636dffc5e25e2bfa8d6350bc8eca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mkdocs >=1.1.0,<2
    - lxml >=4.7.0

test:
  imports:
    - mkdocs_video
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/soulless-viewer/mkdocs-video
  summary: MkDocs Video plugin
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
