schema_version: 1

context:
  name: mkdocs-video
  version: 1.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mkdocs-video-${{ version }}.tar.gz
  sha256: 0defc018f4b7927f8afffc4d8e039c84dfba636dffc5e25e2bfa8d6350bc8eca

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - mkdocs >=1.1.0,<2
    - lxml >=4.7.0

tests:
  - python:
      imports:
        - mkdocs_video
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: MkDocs Video plugin
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/soulless-viewer/mkdocs-video

extra:
  recipe-maintainers:
    - pavelzw
